services:
    - name: frontend
      type: web
      env: docker
      rootDir: frontend
      dockerfilePath: ./frontend/Dockerfile.render
      envVars:
          - key: NEXT_PUBLIC_API_URL
            value: https://backend-smuw.onrender.com
          - key: NEXT_TELEMETRY_DISABLED
            value: 1
          - key: NODE_ENV
            value: production
      autoDeploy: true

    - name: backend
      type: web
      env: docker
      rootDir: backend
      dockerfilePath: ./backend/Dockerfile.render
      envVars:
          - key: DATABASE_URL
            value: ${DATABASE_URL}
          - key: PORT
            value: 5000
          - key: FRONTEND_URL
            value: https://frontend-cmlg.onrender.com
          - key: NODE_ENV
            value: production
          - key: JWT_SECRET
            value: ${JWT_SECRET}
      autoDeploy: true
      healthCheckPath: /health
      buildCommand: yarn prisma generate
